In [15]:
import csv
import numpy as np

# import nyc_taxi.csv as a list of lists
f = open("nyc_taxis.csv", "r")
taxi_list = list(csv.reader(f))

# remove the header row
taxi_list = taxi_list[1:]

# convert all values to floats
converted_taxi_list = []
for row in taxi_list:
    converted_row = []
    for item in row:
        converted_row.append(float(item))
    converted_taxi_list.append(converted_row)

# start writing your code below this comment

taxi = np.array(converted_taxi_list)




In [4]:
taxi_five = taxi[:5]
taxi_ten = taxi[:10]
print(taxi_ten)
print(taxi_five.shape)

[[2.0160e+03 1.0000e+00 1.0000e+00 5.0000e+00 0.0000e+00 2.0000e+00
  4.0000e+00 2.1000e+01 2.0370e+03 5.2000e+01 8.0000e-01 5.5400e+00
  1.1650e+01 6.9990e+01 1.0000e+00]
 [2.0160e+03 1.0000e+00 1.0000e+00 5.0000e+00 0.0000e+00 2.0000e+00
  1.0000e+00 1.6290e+01 1.5200e+03 4.5000e+01 1.3000e+00 0.0000e+00
  8.0000e+00 5.4300e+01 1.0000e+00]
 [2.0160e+03 1.0000e+00 1.0000e+00 5.0000e+00 0.0000e+00 2.0000e+00
  6.0000e+00 1.2700e+01 1.4620e+03 3.6500e+01 1.3000e+00 0.0000e+00
  0.0000e+00 3.7800e+01 2.0000e+00]
 [2.0160e+03 1.0000e+00 1.0000e+00 5.0000e+00 0.0000e+00 2.0000e+00
  6.0000e+00 8.7000e+00 1.2100e+03 2.6000e+01 1.3000e+00 0.0000e+00
  5.4600e+00 3.2760e+01 1.0000e+00]
 [2.0160e+03 1.0000e+00 1.0000e+00 5.0000e+00 0.0000e+00 2.0000e+00
  6.0000e+00 5.5600e+00 7.5900e+02 1.7500e+01 1.3000e+00 0.0000e+00
  0.0000e+00 1.8800e+01 2.0000e+00]
 [2.0160e+03 1.0000e+00 1.0000e+00 5.0000e+00 0.0000e+00 4.0000e+00
  2.0000e+00 2.1450e+01 2.0040e+03 5.2000e+01 8.0000e-01 0.0000e+00
  5.

In [7]:
lenthg = len(taxi)
row_0 = taxi[0]
rows_391_to_500 = taxi[391:501, :]
row_21_column_5 = taxi[21,5]

print(row_21_column_5)
print(rows_391_to_500)

4.0
[[2.016e+03 1.000e+00 2.000e+00 ... 0.000e+00 2.630e+01 2.000e+00]
 [2.016e+03 1.000e+00 2.000e+00 ... 3.000e+00 3.030e+01 1.000e+00]
 [2.016e+03 1.000e+00 2.000e+00 ... 6.670e+00 4.001e+01 1.000e+00]
 ...
 [2.016e+03 1.000e+00 2.000e+00 ... 4.960e+00 2.976e+01 1.000e+00]
 [2.016e+03 1.000e+00 2.000e+00 ... 0.000e+00 3.284e+01 2.000e+00]
 [2.016e+03 1.000e+00 2.000e+00 ... 7.050e+00 4.239e+01 1.000e+00]]


In [8]:

columns_1_4_7 = taxi[:,[1,4,7]]

row_99_columns_5_to_8 = taxi[99,5:9]

rows_100_to_200_column_14 = taxi[100:201,14]

In [9]:
trip_distance_miles = taxi[:,7]
trip_length_seconds = taxi[:,8]

trip_length_hours = trip_length_seconds / 3600 # 3600 seconds is one hour

trip_mph = trip_distance_miles / trip_length_hours

In [10]:
mph_min = trip_mph.min()
mph_max = trip_mph.max()
mph_mean = trip_mph.mean()


In [11]:
taxi_column_means = taxi.mean(axis=0)

In [12]:
# These `ones` and `zeros` variables
# are different from the ones in the
# main lesson example

print(ones)
print(zeros)
print() # creates a space in our output

print(ones.shape)
print(zeros.shape)
print()

zeros_2d = np.expand_dims(zeros,axis=1)

print(zeros_2d)
print(zeros_2d.shape)
print()
print('\n')
combined = np.concatenate([ones,zeros_2d],axis=1)
print(combined)
print()

# the `trip_mph` variable is still available from the
# previous screen
trip_mph_2d = np.expand_dims(trip_mph,axis=1)

taxi = np.concatenate([taxi,trip_mph_2d],axis=1)

NameError: name 'ones' is not defined

In [19]:
print(np.shape(taxi))

(89560, 15)


In [21]:

last_column = taxi[:,15]

taxi_order = np.argsort(last_column)

taxi_sorted = taxi[taxi_order]

print(taxi_sorted)


IndexError: index 15 is out of bounds for axis 1 with size 15

In [22]:
import numpy as np
taxi = np.genfromtxt('nyc_taxis.csv',delimiter=',',skip_header=1)

In [26]:
pickup_month = taxi[:,1]

january_bool = pickup_month == 1
january = pickup_month[january_bool]
january_rides = january.shape[0]

february_bool = pickup_month == 2

february = pickup_month[february_bool]

february_rides = february.shape

march_bool = pickup_month == 3

march = pickup_month[march_bool]

march_rides = march.shape



In [27]:
print(taxi)

[[2.016e+03 1.000e+00 1.000e+00 ... 1.165e+01 6.999e+01 1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 8.000e+00 5.430e+01 1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 0.000e+00 3.780e+01 2.000e+00]
 ...
 [2.016e+03 6.000e+00 3.000e+01 ... 5.000e+00 6.334e+01 1.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 8.950e+00 4.475e+01 1.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 0.000e+00 5.484e+01 2.000e+00]]


In [28]:
tip_amount = taxi[:,12]

tip_bool = tip_amount > 50

top_tips = taxi[tip_bool,5:14]

In [31]:
# this creates a copy of our taxi ndarray
import numpy as np
taxi_modified = taxi.copy()


taxi_modified[28214,5] = 1

taxi_modified[:,0] = 16

taxi_modified[1800:1802,7] = np.mean(taxi_modified[:,7], axis=0)

print(taxi_modified[1800:1802,7])
print(taxi[1800:1802,7])

[12.66742608 12.66742608]
[9.88 8.6 ]


In [35]:
c = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

c[c[:,1] > 2,1] = 99

print(c)

[[ 1  2  3]
 [ 4 99  6]
 [ 7 99  9]]


In [36]:
# this creates a copy of our taxi ndarray
taxi_modified = taxi.copy()

# create a new column filled with `0`.
zeros = np.zeros([taxi_modified.shape[0], 1])
taxi_modified = np.concatenate([taxi, zeros], axis=1)
print(taxi_modified)

#for rows in taxi_modified[:,5]:
#   if rows == 2:

taxi_modified[taxi_modified[:,5] == 2, 15] = 1
taxi_modified[taxi_modified[:,5] == 3, 15] = 1
taxi_modified[taxi_modified[:,5] == 5, 15] = 1


[[2.016e+03 1.000e+00 1.000e+00 ... 6.999e+01 1.000e+00 0.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 5.430e+01 1.000e+00 0.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 3.780e+01 2.000e+00 0.000e+00]
 ...
 [2.016e+03 6.000e+00 3.000e+01 ... 6.334e+01 1.000e+00 0.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 4.475e+01 1.000e+00 0.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 5.484e+01 2.000e+00 0.000e+00]]


In [39]:
jfk = taxi[[taxi[:,6] == 2]]
jfk_count = jfk.shape[0]

laguardia = taxi[[taxi[:,6] == 3]]

laguardia_count = laguardia.shape[0]

newark  = taxi[[taxi[:,6] == 5]]
newark_count = newark.shape[0]

print(newark_count)

63


/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  """Entry point for launching an IPython kernel.
/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  after removing the cwd from sys.path.
/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as 

In [40]:
trip_mph = taxi[:,7] / (taxi[:,8] / 3600)

#print(np.shape(trip_mph))
#print(trip_mph)
#taxi_1 = np.expand_dims(trip_mph, axis=1)

#taxi = np.concatenate([taxi,taxi_1],axis=1)

#print(taxi)
cleaned_taxi = taxi[trip_mph < 100]

mean_distance = np.mean(cleaned_taxi[:,7])

mean_length = np.mean(cleaned_taxi[:,8])

mean_total_amount = np.mean(cleaned_taxi[:,13])

#trip_clean = (trip_mph < 100)

#mean_mph = np.mean(trip_mph < 100)
mean_mph = trip_mph[trip_mph < 100].mean()